info:
  project:
    name: ded-msa-account-movement
    version: 1.0.0
spring:
  profiles:
    active: local
  application:
    name: ded-msa-account-movement
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: business_banking_model_order
        dialect: org.hibernate.dialect.SQLServerDialect
  datasource:
    driver-class-name: org.postgresql.Driver