server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proof-bank
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/proof-bank
    username: postgres
    password: root
http-client:
  api:
    client-customer:
      base-url: http://127.0.0.1:8082/