info:
  project:
    name: ded-msa-account-movement
    version: 1.0.0
spring:
  profiles:
    active: local
  application:
    name: ded-msa-account-movement
  sql:
    init:
      mode: embedded
      platform: postgres
  datasource:
    driver-class-name: org.postgresql.Driver