services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: proof-bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  ded-msa-customer:
    build:
      context: ./ded-msa-customer
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: r2dbc:postgresql://postgres:5432/proof-bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend
    depends_on:
      - postgres

  ded-msa-account-movement:
    build:
      context: ./ded-msa-account-movement
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_POSTGRES_URL: r2dbc:postgresql://postgres:5432/proof-bank
      SPRING_DATASOURCE_POSTGRES_USERNAME: postgres
      SPRING_DATASOURCE_POSTGRES_PASSWORD: root
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge