info:
  project:
    name: ded-msa-customer
    version: 1.0.0
spring:
  profiles:
    active: local
  application:
    name: ded-msa-customer
  sql:
    init:
      mode: embedded
      platform: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
test:
  customer:
    base-path:
      path: /customers