info:
  project:
    name: ded-msa-customer
    version: 1.0.0
spring:
  profiles:
    active: local
  application:
    name: ded-msa-customer
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: business_banking_model_order
        dialect: org.hibernate.dialect.SQLServerDialect
  datasource:
    driver-class-name: org.postgresql.Driver
test:
  customer:
    base-path:
      path: /customers