server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/proof-bank
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/proof-bank
    username: postgres
    password: root