-- DROP SEQUENCE public.account_id_seq;

CREATE SEQUENCE public.account_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE public.customer_id_seq;

CREATE SEQUENCE public.customer_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE public.movement_id_seq;

CREATE SEQUENCE public.movement_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE public.person_id_seq;

CREATE SEQUENCE public.person_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;-- public.account definition

-- Drop table

-- DROP TABLE public.account;

CREATE TABLE public.account (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                account_number varchar NOT NULL,
                                account_type varchar NULL,
                                opening_balance numeric NOT NULL,
                                status varchar NULL,
                                customer_id varchar NULL,
                                CONSTRAINT account_pk PRIMARY KEY (id),
                                CONSTRAINT account_unique UNIQUE (account_number)
);


-- public.movement definition

-- Drop table

-- DROP TABLE public.movement;

CREATE TABLE public.movement (
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 account_number varchar NULL,
                                 movement_date timestamptz NULL,
                                 movement_type varchar NULL,
                                 amount numeric NOT NULL,
                                 balance numeric NOT NULL,
                                 movement_uuid varchar NOT NULL,
                                 CONSTRAINT movement_pk PRIMARY KEY (id),
                                 CONSTRAINT movement_unique UNIQUE (movement_uuid)
);


-- public.person definition

-- Drop table

-- DROP TABLE public.person;

CREATE TABLE public.person (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               "name" varchar NOT NULL,
                               gender varchar NULL,
                               age int4 NULL,
                               address varchar NULL,
                               phone varchar NULL,
                               identification varchar NOT NULL,
                               CONSTRAINT person_pk PRIMARY KEY (id),
                               CONSTRAINT person_unique UNIQUE (identification)
);


-- public.customer definition

-- Drop table

-- DROP TABLE public.customer;

CREATE TABLE public.customer (
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 person_id int8 NOT NULL,
                                 "password" varchar NULL,
                                 status varchar NULL,
                                 CONSTRAINT customer_pk PRIMARY KEY (id),
                                 CONSTRAINT customer_unique UNIQUE (person_id),
                                 CONSTRAINT customer_person_fk FOREIGN KEY (person_id) REFERENCES public.person(id)
);